name: MERN CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    #########################
    # 1️⃣ Checkout repo
    #########################
    - name: Checkout code
      uses: actions/checkout@v3

    #########################
    # 2️⃣ Setup Node
    #########################
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    #########################
    # 3️⃣ Frontend Deployment
    #########################
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy frontend to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: frontend/dist

    #########################
    # 4️⃣ Backend Deployment
    #########################
    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Run backend tests
      run: |
        cd backend
        npm test || echo "No tests"

    - name: Deploy backend to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          # Navigate to backend folder on EC2
          cd ~/repo/backend
          # Pull latest code from GitHub
          git pull origin main
          # Install dependencies
          npm install
          # Restart backend with PM2, or start if not running
          pm2 restart backend || pm2 start index.js --name backend
